apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/mohdumar321/umar-jenkins-x:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/mohdumar321/umar-jenkins-x:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: umar-jenkins-x
        chartPath: charts/umar-jenkins-x
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/mohdumar321/umar-jenkins-x"
          image.tag: "{{.TAG}}"
